create table if not exists alunos (
  id bigint generated by default as identity primary key,
  nome text not null,
  idade integer,
  nome_norm text,
  created_at timestamptz not null default now()
);

create index if not exists idx_alunos_nome_norm_idade
on alunos(nome_norm, idade);

create table if not exists redacoes (
  id bigint generated by default as identity primary key,
  aluno_id bigint not null references alunos(id) on delete cascade,
  tipo text,
  tema text,
  titulo text,
  texto_original text not null,
  review text not null,
  orientacao_adulto text,
  created_at timestamptz not null default now()
);

create index if not exists idx_redacoes_aluno_data
on redacoes(aluno_id, created_at desc);

create table if not exists leituras (
  id bigint generated by default as identity primary key,
  aluno_id bigint not null references alunos(id) on delete cascade,
  titulo text,
  texto text not null,
  idade integer,
  read_time_ms integer,
  total_questions integer,
  questions_json jsonb,
  feedback text,
  created_at timestamptz not null default now()
);

create table if not exists leitura_respostas (
  id bigint generated by default as identity primary key,
  leitura_id bigint not null references leituras(id) on delete cascade,
  pergunta_index integer,
  pergunta text,
  resposta text,
  correta boolean,
  tempo_ms integer,
  tags_json jsonb,
  created_at timestamptz not null default now()
);

alter table alunos enable row level security;
alter table redacoes enable row level security;
alter table leituras enable row level security;
alter table leitura_respostas enable row level security;

drop policy if exists "service_role_all_alunos" on alunos;
create policy "service_role_all_alunos" on alunos for all to service_role using (true) with check (true);

drop policy if exists "service_role_all_redacoes" on redacoes;
create policy "service_role_all_redacoes" on redacoes for all to service_role using (true) with check (true);

drop policy if exists "service_role_all_leituras" on leituras;
create policy "service_role_all_leituras" on leituras for all to service_role using (true) with check (true);

drop policy if exists "service_role_all_leitura_respostas" on leitura_respostas;
create policy "service_role_all_leitura_respostas" on leitura_respostas for all to service_role using (true) with check (true);
